# Generated by Django 5.1.1 on 2024-09-27 00:33

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cliente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cpf', models.CharField(max_length=11, unique=True)),
                ('nome', models.CharField(max_length=120)),
                ('data_nascimento', models.DateField()),
                ('obs', models.TextField(blank=True, null=True)),
            ],
        ),
    ]
